"""Terraform PR Generator — creates GitHub PRs with IaC changes.

Given an approved GovernanceVerdict, generates the appropriate Terraform
configuration change and opens a PR against the IaC repository.

The PR body includes:
- The governance verdict (decision, SRI composite, reason)
- The proposed action details
- A Terraform change stub with reviewer instructions
- A link to the dashboard drilldown

This module requires PyGithub: pip install PyGithub>=2.1.0
Env vars: GITHUB_TOKEN, IAC_GITHUB_REPO (or settings equivalents).
"""

import asyncio
import logging
from datetime import datetime, timezone

from src.config import settings
from src.core.models import ExecutionRecord, ExecutionStatus, GovernanceVerdict

logger = logging.getLogger(__name__)


class TerraformPRGenerator:
    """Generate GitHub PRs with Terraform changes for approved verdicts.

    All GitHub API calls are synchronous (PyGithub does not have an async
    client).  They are run via ``asyncio.to_thread()`` so the event loop
    is not blocked.
    """

    def __init__(self) -> None:
        self._token = settings.github_token
        self._repo_name = settings.iac_github_repo
        self._default_iac_path = settings.iac_terraform_path
        self._dashboard_url = settings.dashboard_url

    async def create_pr(
        self,
        verdict: GovernanceVerdict,
        record: ExecutionRecord,
    ) -> ExecutionRecord:
        """Create a GitHub PR with the proposed Terraform change.

        Runs the blocking GitHub API calls in a thread pool via
        ``asyncio.to_thread()``.

        Args:
            verdict: The approved governance verdict.
            record: The ExecutionRecord to update with PR URL / status.

        Returns:
            Updated ExecutionRecord.
        """
        if not self._token:
            logger.warning(
                "TerraformPRGenerator: GITHUB_TOKEN not set — cannot create PR"
            )
            record.status = ExecutionStatus.manual_required
            record.notes = "GITHUB_TOKEN not configured — manual execution required"
            return record

        if not self._repo_name:
            logger.warning(
                "TerraformPRGenerator: IAC_GITHUB_REPO not set — cannot create PR"
            )
            record.status = ExecutionStatus.manual_required
            record.notes = "IAC_GITHUB_REPO not configured — manual execution required"
            return record

        return await asyncio.to_thread(self._create_pr_sync, verdict, record)

    # ------------------------------------------------------------------
    # Private helpers (sync, run via asyncio.to_thread)
    # ------------------------------------------------------------------

    def _create_pr_sync(
        self,
        verdict: GovernanceVerdict,
        record: ExecutionRecord,
    ) -> ExecutionRecord:
        """Blocking GitHub API calls — called from asyncio.to_thread."""
        from github import Github, GithubException  # noqa: PLC0415 (lazy import — PyGithub optional)

        action = verdict.proposed_action
        resource_id = action.target.resource_id
        resource_short = resource_id.split("/")[-1] if "/" in resource_id else resource_id

        try:
            gh = Github(self._token)
            repo = gh.get_repo(self._repo_name)

            # Build branch name: ruriskry/approved/{resource}-{short-action-id}
            branch_name = (
                f"ruriskry/approved/{resource_short}-{verdict.action_id[:8]}"
            )

            # Get default branch SHA for the new branch base
            default_branch = repo.default_branch
            base_ref = repo.get_git_ref(f"heads/{default_branch}")
            base_sha = base_ref.object.sha

            # Create branch
            repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)

            # Generate Terraform stub
            tf_content = self._generate_terraform_stub(verdict, record)
            iac_path = record.iac_path or self._default_iac_path
            tf_file_path = (
                f"{iac_path}/ruriskry_approved_{resource_short}_{verdict.action_id[:8]}.tf"
            )

            commit_message = (
                f"ruriskry: {action.action_type.value} {resource_short} "
                f"(SRI {verdict.skry_risk_index.sri_composite:.1f}, APPROVED)\n\n"
                f"Auto-generated by RuriSkry Governance Engine.\n"
                f"Action ID: {verdict.action_id}\n"
                f"Proposing agent: {action.agent_id}\n"
                f"Reason: {action.reason}"
            )

            repo.create_file(
                path=tf_file_path,
                message=commit_message,
                content=tf_content.encode(),
                branch=branch_name,
            )

            # Build PR
            pr_title = (
                f"[RuriSkry] "
                f"{action.action_type.value.replace('_', ' ').title()}: "
                f"{resource_short}"
            )
            pr_body = self._build_pr_body(verdict, record)

            pr = repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=default_branch,
            )

            # Add labels (best-effort — labels may not exist in the repo yet)
            try:
                pr.add_to_labels("ruriskry", "auto-generated", "governance-approved")
            except GithubException:
                pass

            record.status = ExecutionStatus.pr_created
            record.pr_url = pr.html_url
            record.pr_number = pr.number
            record.updated_at = datetime.now(timezone.utc)

            logger.info(
                "TerraformPRGenerator: PR #%d created — %s",
                pr.number,
                pr.html_url,
            )

        except GithubException as exc:
            logger.error("TerraformPRGenerator: GitHub API error — %s", exc)
            record.status = ExecutionStatus.failed
            record.notes = f"GitHub API error: {exc}"
            record.updated_at = datetime.now(timezone.utc)

        except Exception as exc:  # noqa: BLE001
            logger.error("TerraformPRGenerator: unexpected error — %s", exc)
            record.status = ExecutionStatus.failed
            record.notes = f"Error creating PR: {exc}"
            record.updated_at = datetime.now(timezone.utc)

        return record

    def _generate_terraform_stub(
        self,
        verdict: GovernanceVerdict,
        record: ExecutionRecord,
    ) -> str:
        """Generate a Terraform HCL stub documenting the approved change.

        This creates a self-documenting stub file that tells the reviewer
        exactly what change to implement.  For a production system you would:
        - Parse the existing .tf files (use the ``hcl2`` library)
        - Generate a targeted diff against the existing resource block
        - Run terraform-cdk for typed configuration changes

        The stub approach is safe: it creates no actual Terraform resources
        but documents the change clearly with a reviewer checklist.
        """
        action = verdict.proposed_action
        resource_id = action.target.resource_id
        resource_short = resource_id.split("/")[-1] if "/" in resource_id else resource_id
        action_type = action.action_type.value
        sri = verdict.skry_risk_index

        header = f"""# =============================================================================
# RuriSkry Governance — Approved Action Stub
# =============================================================================
# Action:       {action_type}
# Resource:     {resource_short}
# Full ID:      {resource_id}
# Proposing Agent: {action.agent_id}
# SRI Composite: {sri.sri_composite:.1f} / 100
#   Infrastructure: {sri.sri_infrastructure:.1f}
#   Policy:         {sri.sri_policy:.1f}
#   Historical:     {sri.sri_historical:.1f}
#   Cost:           {sri.sri_cost:.1f}
# Verdict:      APPROVED
# Reason:       {action.reason}
# Action ID:    {verdict.action_id}
# IaC Tool:     {record.iac_tool}
# IaC Path:     {record.iac_path}
# Generated:    {datetime.now(timezone.utc).isoformat()}
# =============================================================================
#
# REVIEWER INSTRUCTIONS:
# 1. Run `terraform plan` in CI to preview the actual changes.
# 2. Locate the existing resource block for "{resource_short}" in this directory.
# 3. Apply the change described below, then DELETE this stub file.
# 4. The governance verdict is logged in Cosmos DB (Action ID above).
# =============================================================================

"""
        # Action-specific guidance
        if action_type == "scale_up":
            proposed_sku = action.target.proposed_sku or "<new_vm_size>"
            current_sku = action.target.current_sku or "<current_vm_size>"
            return header + f"""# CHANGE REQUIRED: Scale up {resource_short}
# Current SKU:  {current_sku}
# Proposed SKU: {proposed_sku}
#
# In the existing resource block for {resource_short}, update:
#   size = "{proposed_sku}"
# Then delete this file.
"""

        elif action_type == "scale_down":
            proposed_sku = action.target.proposed_sku or "<smaller_vm_size>"
            current_sku = action.target.current_sku or "<current_vm_size>"
            return header + f"""# CHANGE REQUIRED: Scale down {resource_short}
# Current SKU:  {current_sku}
# Proposed SKU: {proposed_sku}
#
# In the existing resource block for {resource_short}, update:
#   size = "{proposed_sku}"
# Then delete this file.
"""

        elif action_type == "delete_resource":
            return header + f"""# CHANGE REQUIRED: Delete {resource_short}
# Agent reason: {action.reason}
#
# WARNING: Removal is IRREVERSIBLE.  Before proceeding:
# - Confirm no live dependencies exist
# - Back up any critical data
#
# In the existing resource block for {resource_short}:
# - Comment out or remove the entire resource block
# - Run `terraform plan` to confirm only this resource is removed
# Then delete this file.
"""

        elif action_type == "modify_nsg":
            return header + f"""# CHANGE REQUIRED: NSG modification for {resource_short}
# Agent reason: {action.reason}
#
# In the existing azurerm_network_security_group or
# azurerm_network_security_rule block for {resource_short}:
# - Add/modify the security rule as described above
# Then delete this file.
"""

        elif action_type == "restart_service":
            return header + f"""# CHANGE REQUIRED: Restart service on {resource_short}
# Agent reason: {action.reason}
#
# NOTE: Service restarts are typically not managed via Terraform.
# Consider:
# - Using az vm restart or az webapp restart directly
# - Adding a null_resource with a remote-exec provisioner
# Then delete this file.
"""

        elif action_type == "update_config":
            return header + f"""# CHANGE REQUIRED: Configuration update for {resource_short}
# Agent reason: {action.reason}
#
# Apply the configuration change described above to the
# resource block for {resource_short} in this Terraform directory.
# Then delete this file.
"""

        else:
            return header + f"""# CHANGE REQUIRED: {action_type} on {resource_short}
# Agent reason: {action.reason}
#
# Apply the change described above.  Then delete this file.
"""

    def _build_pr_body(
        self,
        verdict: GovernanceVerdict,
        record: ExecutionRecord,
    ) -> str:
        """Build the full GitHub PR description with governance context."""
        action = verdict.proposed_action
        sri = verdict.skry_risk_index
        resource_id = action.target.resource_id
        resource_short = resource_id.split("/")[-1] if "/" in resource_id else resource_id
        dashboard_link = self._dashboard_url or ""

        return f"""## RuriSkry Governance — Approved Action

**This PR was auto-generated by the RuriSkry Governance Engine.**
A human must review and merge it to execute the change safely via Terraform.
No resources are modified until a human merges this PR.

---

### Governance Verdict

| Field | Value |
|-------|-------|
| Decision | **APPROVED** |
| SRI™ Composite | **{sri.sri_composite:.1f}** / 100 |
| SRI Infrastructure | {sri.sri_infrastructure:.1f} |
| SRI Policy | {sri.sri_policy:.1f} |
| SRI Historical | {sri.sri_historical:.1f} |
| SRI Financial | {sri.sri_cost:.1f} |
| Verdict Reason | {verdict.reason} |

---

### Proposed Action

| Field | Value |
|-------|-------|
| Resource | `{resource_short}` |
| Full Resource ID | `{resource_id}` |
| Action Type | {action.action_type.value.replace('_', ' ')} |
| Proposing Agent | `{action.agent_id}` |
| Reason | {action.reason} |
| Urgency | {action.urgency.value} |

---

### IaC Context

| Field | Value |
|-------|-------|
| IaC Tool | {record.iac_tool} |
| IaC Path | `{record.iac_path}` |
| Execution ID | `{record.execution_id}` |
| Action ID | `{verdict.action_id}` |

---

### Reviewer Checklist

- [ ] Verify the resource ID matches the intended target
- [ ] Review the Terraform change stub in this PR
- [ ] Run `terraform plan` in CI to preview the actual changes
- [ ] Confirm no unrelated resources are affected
- [ ] Apply the change to the existing .tf file and delete the stub
- [ ] Merge to apply via CI/CD

{f'[View in RuriSkry Dashboard]({dashboard_link})' if dashboard_link else ''}

---
*Auto-generated by [RuriSkry Governance Engine](https://github.com/{record.iac_repo})*
"""
