#!/usr/bin/env bash
# =============================================================================
# setup_env.sh - Auto-generate .env from Terraform outputs
# =============================================================================
# Default mode (recommended):
#   bash scripts/setup_env.sh
#   Writes endpoint values + Key Vault secret names (no plaintext keys).
#
# Local override mode:
#   bash scripts/setup_env.sh --include-keys
#   Also writes raw API keys into .env (convenient for local testing).
# =============================================================================

set -euo pipefail

INCLUDE_KEYS=false
if [[ "${1:-}" == "--include-keys" ]]; then
  INCLUDE_KEYS=true
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TERRAFORM_DIR="$PROJECT_ROOT/infrastructure/terraform"
ENV_FILE="$PROJECT_ROOT/.env"

echo "Reading Terraform outputs from $TERRAFORM_DIR ..."
cd "$TERRAFORM_DIR"

if [ ! -f "terraform.tfstate" ]; then
  echo "ERROR: terraform.tfstate not found."
  echo "Run 'terraform apply' in infrastructure/terraform/ first."
  exit 1
fi

TF_JSON=$(terraform output -json)

tf_value() {
  echo "$TF_JSON" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$1',{}).get('value',''))"
}

# Non-sensitive outputs
FOUNDRY_ENDPOINT=$(tf_value foundry_endpoint)
FOUNDRY_DEPLOYMENT=$(tf_value foundry_deployment)
SEARCH_ENDPOINT=$(tf_value search_endpoint)
SEARCH_INDEX=$(tf_value search_index_name)
COSMOS_ENDPOINT=$(tf_value cosmos_endpoint)
COSMOS_DATABASE=$(tf_value cosmos_database)
COSMOS_CONTAINER=$(tf_value cosmos_container_decisions)
LOG_WORKSPACE_ID=$(tf_value log_analytics_workspace_id)
KEYVAULT_URL=$(tf_value keyvault_url)
FOUNDRY_KEY_SECRET_NAME=$(tf_value keyvault_secret_name_foundry_key)
SEARCH_KEY_SECRET_NAME=$(tf_value keyvault_secret_name_search_key)
COSMOS_KEY_SECRET_NAME=$(tf_value keyvault_secret_name_cosmos_key)

# Optional plaintext keys
FOUNDRY_KEY=""
SEARCH_KEY=""
COSMOS_KEY=""
if [ "$INCLUDE_KEYS" = true ]; then
  echo "Including plaintext service keys in .env (local/dev mode)."
  FOUNDRY_KEY=$(terraform output -raw foundry_primary_key)
  SEARCH_KEY=$(terraform output -raw search_primary_key)
  COSMOS_KEY=$(terraform output -raw cosmos_primary_key)
fi

cd "$PROJECT_ROOT"

cat > "$ENV_FILE" <<EOF
# =============================================================
# SentinelLayer .env - auto-generated by scripts/setup_env.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================

# --- Mock vs Azure mode ---
USE_LOCAL_MOCKS=false

# --- Microsoft Foundry ---
AZURE_OPENAI_ENDPOINT=$FOUNDRY_ENDPOINT
AZURE_OPENAI_API_KEY=$FOUNDRY_KEY
AZURE_OPENAI_API_KEY_SECRET_NAME=$FOUNDRY_KEY_SECRET_NAME
AZURE_OPENAI_DEPLOYMENT=$FOUNDRY_DEPLOYMENT
AZURE_OPENAI_API_VERSION=2025-01-01-preview

# --- Azure AI Search ---
AZURE_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
AZURE_SEARCH_API_KEY=$SEARCH_KEY
AZURE_SEARCH_API_KEY_SECRET_NAME=$SEARCH_KEY_SECRET_NAME
AZURE_SEARCH_INDEX=$SEARCH_INDEX

# --- Azure Cosmos DB (SQL API) ---
COSMOS_ENDPOINT=$COSMOS_ENDPOINT
COSMOS_KEY=$COSMOS_KEY
COSMOS_KEY_SECRET_NAME=$COSMOS_KEY_SECRET_NAME
COSMOS_DATABASE=$COSMOS_DATABASE
COSMOS_CONTAINER_DECISIONS=$COSMOS_CONTAINER

# --- Azure Resource Graph ---
# Fill these manually (terraform does not manage them)
AZURE_SUBSCRIPTION_ID=<your-subscription-id>
AZURE_TENANT_ID=<your-tenant-id>

# --- Azure Monitor ---
LOG_ANALYTICS_WORKSPACE_ID=$LOG_WORKSPACE_ID

# --- Azure Key Vault / Managed Identity ---
AZURE_KEYVAULT_URL=$KEYVAULT_URL
# Optional for user-assigned managed identity. Leave empty for system-assigned.
AZURE_MANAGED_IDENTITY_CLIENT_ID=

# --- SRI thresholds ---
SRI_AUTO_APPROVE_THRESHOLD=25
SRI_HUMAN_REVIEW_THRESHOLD=60
EOF

echo ""
echo ".env written to $ENV_FILE"
echo ""
echo "ACTION REQUIRED:"
echo "  1) Fill these values in .env:"
echo "     AZURE_SUBSCRIPTION_ID=<your-subscription-id>"
echo "     AZURE_TENANT_ID=<your-tenant-id>"
echo "  2) Ensure your runtime identity can read Key Vault secrets (Get/List)."
echo ""
echo "Find subscription/tenant with:"
echo "  az account show --query '{subscriptionId:id, tenantId:tenantId}'"
echo ""
if [ "$INCLUDE_KEYS" = false ]; then
  echo "Secure mode used: keys were NOT written to .env."
  echo "Use '--include-keys' only for local/dev fallback."
fi
echo ""
echo "Seed search data:"
echo "  python scripts/seed_data.py"
