#!/usr/bin/env bash
# =============================================================================
# setup_env.sh — Auto-generate .env from Terraform outputs
# =============================================================================
# Run from the project root AFTER `terraform apply` has completed:
#
#   bash scripts/setup_env.sh
#
# What this script does:
#   1. Changes into infrastructure/terraform/
#   2. Reads all Terraform output values (including secrets)
#   3. Writes a .env file in the project root
#   4. Reminds you to fill in the two values Terraform doesn't know
#      (AZURE_SUBSCRIPTION_ID and AZURE_TENANT_ID)
#
# Requirements:
#   - Terraform CLI installed and in PATH
#   - `terraform apply` already completed successfully
#   - Python 3 installed (used to parse JSON output)
# =============================================================================

set -euo pipefail   # exit on any error, undefined variable, or pipe failure

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TERRAFORM_DIR="$PROJECT_ROOT/infrastructure/terraform"
ENV_FILE="$PROJECT_ROOT/.env"

# ---------------------------------------------------------------------------
# Read Terraform outputs
# ---------------------------------------------------------------------------

echo "Reading Terraform outputs from $TERRAFORM_DIR ..."
cd "$TERRAFORM_DIR"

# Check that Terraform state exists
if [ ! -f "terraform.tfstate" ]; then
  echo "ERROR: terraform.tfstate not found."
  echo "       Run 'terraform apply' in infrastructure/terraform/ first."
  exit 1
fi

# Read the full JSON output once (avoids multiple terraform calls)
TF_JSON=$(terraform output -json)

# Helper function: extract a non-sensitive value from the JSON blob
tf_value() {
  echo "$TF_JSON" | python3 -c "import sys, json; d=json.load(sys.stdin); print(d['$1']['value'])"
}

# Sensitive values must be read with terraform output -raw (bypasses masking)
echo "Reading sensitive values (API keys) ..."
SEARCH_KEY=$(terraform output -raw search_primary_key)
COSMOS_KEY=$(terraform output -raw cosmos_primary_key)

# Non-sensitive values
SEARCH_ENDPOINT=$(tf_value search_endpoint)
COSMOS_ENDPOINT=$(tf_value cosmos_endpoint)
COSMOS_DATABASE=$(tf_value cosmos_database)
COSMOS_CONTAINER=$(tf_value cosmos_container_decisions)
LOG_WORKSPACE_ID=$(tf_value log_analytics_workspace_id)
KEYVAULT_URL=$(tf_value keyvault_url)

# Return to project root
cd "$PROJECT_ROOT"

# ---------------------------------------------------------------------------
# Write .env
# ---------------------------------------------------------------------------

cat > "$ENV_FILE" <<EOF
# =============================================================
# SentinelLayer .env — auto-generated by scripts/setup_env.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# DO NOT commit this file — it contains real API keys.
# It is already listed in .gitignore.
# =============================================================

# --- Mock vs Azure mode ---
# Set to false to use real Azure services (this file already has
# all the credentials needed). Set to true to use local JSON files.
USE_LOCAL_MOCKS=false

# --- Microsoft Foundry — GPT-4.1 (fill in manually from the Foundry portal) ---
# Go to https://ai.azure.com → your project → Models → gpt-41 deployment
# Copy the endpoint and API key shown there.
AZURE_OPENAI_ENDPOINT=<paste-your-foundry-endpoint-here>
AZURE_OPENAI_API_KEY=<paste-your-foundry-api-key-here>
AZURE_OPENAI_DEPLOYMENT=gpt-41
AZURE_OPENAI_API_VERSION=2025-01-01-preview

# --- Azure AI Search ---
AZURE_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
AZURE_SEARCH_API_KEY=$SEARCH_KEY
AZURE_SEARCH_INDEX=incident-history

# --- Azure Cosmos DB (SQL API) ---
COSMOS_ENDPOINT=$COSMOS_ENDPOINT
COSMOS_KEY=$COSMOS_KEY
COSMOS_DATABASE=$COSMOS_DATABASE
COSMOS_CONTAINER_DECISIONS=$COSMOS_CONTAINER

# --- Azure Resource Graph ---
# TODO: fill these in manually (terraform doesn't manage these values)
AZURE_SUBSCRIPTION_ID=<your-subscription-id>
AZURE_TENANT_ID=<your-tenant-id>

# --- Azure Monitor ---
LOG_ANALYTICS_WORKSPACE_ID=$LOG_WORKSPACE_ID

# --- Azure Key Vault ---
AZURE_KEYVAULT_URL=$KEYVAULT_URL

# --- SRI™ Thresholds (leave as defaults unless you need to tune) ---
SRI_AUTO_APPROVE_THRESHOLD=25
SRI_HUMAN_REVIEW_THRESHOLD=60
EOF

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo ""
echo "✓ .env written to $ENV_FILE"
echo ""
echo "ACTION REQUIRED — fill in these values manually in .env:"
echo ""
echo "  1. Microsoft Foundry (GPT-4.1) credentials:"
echo "       AZURE_OPENAI_ENDPOINT=https://<your-project>.services.ai.azure.com/"
echo "       AZURE_OPENAI_API_KEY=<key from https://ai.azure.com>"
echo ""
echo "  2. Subscription and tenant IDs:"
echo "       AZURE_SUBSCRIPTION_ID=<your-subscription-id>"
echo "       AZURE_TENANT_ID=<your-tenant-id>"
echo ""
echo "Find subscription/tenant with:"
echo "  az account show --query '{subscriptionId:id, tenantId:tenantId}'"
echo ""
echo "Then upload seed data to Azure AI Search:"
echo "  python scripts/seed_data.py"
