#!/usr/bin/env bash
# =============================================================================
# setup_env.sh - Auto-generate .env from Terraform outputs
# =============================================================================
# Default mode (recommended):
#   bash scripts/setup_env.sh
#   Writes endpoint values + Key Vault secret names (no plaintext keys).
#
# Local override mode:
#   bash scripts/setup_env.sh --include-keys
#   Also writes raw API keys into .env (convenient for local testing).
#
# Non-interactive mode:
#   bash scripts/setup_env.sh --no-prompt
#   Skips prompts and uses Azure CLI defaults when available.
# =============================================================================

set -euo pipefail

INCLUDE_KEYS=false
NO_PROMPT=false

for arg in "$@"; do
  case "$arg" in
    --include-keys)
      INCLUDE_KEYS=true
      ;;
    --no-prompt)
      NO_PROMPT=true
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TERRAFORM_DIR="$PROJECT_ROOT/infrastructure/terraform"
ENV_FILE="$PROJECT_ROOT/.env"

echo "Reading Terraform outputs from $TERRAFORM_DIR ..."
cd "$TERRAFORM_DIR"

if ! command -v terraform >/dev/null 2>&1; then
  echo "ERROR: terraform command not found in PATH for this shell."
  echo "Use a shell where terraform is installed, or run from PowerShell."
  exit 1
fi

if [ ! -f "terraform.tfstate" ]; then
  echo "ERROR: terraform.tfstate not found."
  echo "Run 'terraform apply' in infrastructure/terraform/ first."
  exit 1
fi

tf_raw() {
  terraform output -raw "$1"
}

az_tsv() {
  az account show --query "$1" -o tsv 2>/dev/null || true
}

# Non-sensitive outputs
FOUNDRY_ENDPOINT=$(tf_raw foundry_endpoint)
FOUNDRY_DEPLOYMENT=$(tf_raw foundry_deployment)
SEARCH_ENDPOINT=$(tf_raw search_endpoint)
SEARCH_INDEX=$(tf_raw search_index_name)
COSMOS_ENDPOINT=$(tf_raw cosmos_endpoint)
COSMOS_DATABASE=$(tf_raw cosmos_database)
COSMOS_CONTAINER=$(tf_raw cosmos_container_decisions)
LOG_WORKSPACE_ID=$(tf_raw log_analytics_workspace_id)
KEYVAULT_URL=$(tf_raw keyvault_url)
FOUNDRY_KEY_SECRET_NAME=$(tf_raw keyvault_secret_name_foundry_key)
SEARCH_KEY_SECRET_NAME=$(tf_raw keyvault_secret_name_search_key)
COSMOS_KEY_SECRET_NAME=$(tf_raw keyvault_secret_name_cosmos_key)

# Optional plaintext keys
FOUNDRY_KEY=""
SEARCH_KEY=""
COSMOS_KEY=""
if [ "$INCLUDE_KEYS" = true ]; then
  echo "Including plaintext service keys in .env (local/dev mode)."
  FOUNDRY_KEY=$(terraform output -raw foundry_primary_key)
  SEARCH_KEY=$(terraform output -raw search_primary_key)
  COSMOS_KEY=$(terraform output -raw cosmos_primary_key)
fi

# Subscription and tenant defaults from the current Azure CLI account
DEFAULT_SUBSCRIPTION_ID=$(az_tsv id)
DEFAULT_TENANT_ID=$(az_tsv tenantId)

# Prompt only when attached to an interactive terminal and no --no-prompt flag
SUBSCRIPTION_ID="${DEFAULT_SUBSCRIPTION_ID}"
TENANT_ID="${DEFAULT_TENANT_ID}"

if [ "$NO_PROMPT" = false ] && [ -t 0 ]; then
  echo ""
  echo "Enter Azure account identifiers for .env (press Enter to accept defaults)."
  read -r -p "AZURE_SUBSCRIPTION_ID [${DEFAULT_SUBSCRIPTION_ID:-<your-subscription-id>}]: " INPUT_SUBSCRIPTION_ID
  read -r -p "AZURE_TENANT_ID [${DEFAULT_TENANT_ID:-<your-tenant-id>}]: " INPUT_TENANT_ID

  if [ -n "${INPUT_SUBSCRIPTION_ID}" ]; then
    SUBSCRIPTION_ID="${INPUT_SUBSCRIPTION_ID}"
  fi
  if [ -n "${INPUT_TENANT_ID}" ]; then
    TENANT_ID="${INPUT_TENANT_ID}"
  fi
fi

# Final fallback placeholders if Azure CLI is unavailable and no input provided
SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-<your-subscription-id>}"
TENANT_ID="${TENANT_ID:-<your-tenant-id>}"

cd "$PROJECT_ROOT"

cat > "$ENV_FILE" <<EOF
# =============================================================
# SentinelLayer .env - auto-generated by scripts/setup_env.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================

# --- Mock vs Azure mode ---
USE_LOCAL_MOCKS=false

# --- Microsoft Foundry ---
AZURE_OPENAI_ENDPOINT=$FOUNDRY_ENDPOINT
AZURE_OPENAI_API_KEY=$FOUNDRY_KEY
AZURE_OPENAI_API_KEY_SECRET_NAME=$FOUNDRY_KEY_SECRET_NAME
AZURE_OPENAI_DEPLOYMENT=$FOUNDRY_DEPLOYMENT
AZURE_OPENAI_API_VERSION=2025-01-01-preview

# --- Azure AI Search ---
AZURE_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
AZURE_SEARCH_API_KEY=$SEARCH_KEY
AZURE_SEARCH_API_KEY_SECRET_NAME=$SEARCH_KEY_SECRET_NAME
AZURE_SEARCH_INDEX=$SEARCH_INDEX

# --- Azure Cosmos DB (SQL API) ---
COSMOS_ENDPOINT=$COSMOS_ENDPOINT
COSMOS_KEY=$COSMOS_KEY
COSMOS_KEY_SECRET_NAME=$COSMOS_KEY_SECRET_NAME
COSMOS_DATABASE=$COSMOS_DATABASE
COSMOS_CONTAINER_DECISIONS=$COSMOS_CONTAINER

# --- Azure Resource Graph ---
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
AZURE_TENANT_ID=$TENANT_ID

# --- Azure Monitor ---
LOG_ANALYTICS_WORKSPACE_ID=$LOG_WORKSPACE_ID

# --- Azure Key Vault / Managed Identity ---
AZURE_KEYVAULT_URL=$KEYVAULT_URL
# Optional for user-assigned managed identity. Leave empty for system-assigned.
AZURE_MANAGED_IDENTITY_CLIENT_ID=

# --- SRI thresholds ---
SRI_AUTO_APPROVE_THRESHOLD=25
SRI_HUMAN_REVIEW_THRESHOLD=60
EOF

echo ""
echo ".env written to $ENV_FILE"
echo ""
echo "Configured values:"
echo "  AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"
echo "  AZURE_TENANT_ID=$TENANT_ID"
echo ""
echo "ACTION REQUIRED:"
echo "  Ensure your runtime identity can read Key Vault secrets (Get/List)."
echo ""
if [ "$INCLUDE_KEYS" = false ]; then
  echo "Secure mode used: keys were NOT written to .env."
  echo "Use '--include-keys' only for local/dev fallback."
fi
echo ""
echo "Seed search data:"
echo "  python scripts/seed_data.py"
